// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOoFLNTSW4hRjiNIPNl80wKPliS0zwBok',
    appId: '1:38888572550:web:f22e70336788b1876af307',
    messagingSenderId: '38888572550',
    projectId: 'pricewatch-apk',
    authDomain: 'pricewatch-apk.firebaseapp.com',
    databaseURL: 'https://pricewatch-apk-default-rtdb.firebaseio.com',
    storageBucket: 'pricewatch-apk.firebasestorage.app',
    measurementId: 'G-9Q5ZTB4XV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnvUQvtpOWzgA1Gpfco7SEhEEdxkNlCek',
    appId: '1:38888572550:android:3f42eea6706debdd6af307',
    messagingSenderId: '38888572550',
    projectId: 'pricewatch-apk',
    databaseURL: 'https://pricewatch-apk-default-rtdb.firebaseio.com',
    storageBucket: 'pricewatch-apk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpixoqk1D12gQ1fGojluUtOUNdBW18TtE',
    appId: '1:38888572550:ios:307bb2f7f950213f6af307',
    messagingSenderId: '38888572550',
    projectId: 'pricewatch-apk',
    databaseURL: 'https://pricewatch-apk-default-rtdb.firebaseio.com',
    storageBucket: 'pricewatch-apk.firebasestorage.app',
    iosBundleId: 'com.example.pricewatchApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpixoqk1D12gQ1fGojluUtOUNdBW18TtE',
    appId: '1:38888572550:ios:307bb2f7f950213f6af307',
    messagingSenderId: '38888572550',
    projectId: 'pricewatch-apk',
    databaseURL: 'https://pricewatch-apk-default-rtdb.firebaseio.com',
    storageBucket: 'pricewatch-apk.firebasestorage.app',
    iosBundleId: 'com.example.pricewatchApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOoFLNTSW4hRjiNIPNl80wKPliS0zwBok',
    appId: '1:38888572550:web:af8d4cba312975816af307',
    messagingSenderId: '38888572550',
    projectId: 'pricewatch-apk',
    authDomain: 'pricewatch-apk.firebaseapp.com',
    databaseURL: 'https://pricewatch-apk-default-rtdb.firebaseio.com',
    storageBucket: 'pricewatch-apk.firebasestorage.app',
    measurementId: 'G-FNYX1GFKPT',
  );
}
